export const tuning = {
    seed: 20261009,
    camera: {
        fovYDegrees: 20,
        elevationDegrees: 52,
        azimuthDegrees: 21,
        distance: 30,
        targetOffset: [0, 0, -2.5],
        followRateZ: 7,
        followRateX: 4,
        maxTargetX: 2,
        near: 5,
        far: 80,
    },
    player: {
        start: [0, 0],
        minX: -4, maxX: 4,
        hopSeconds: .15,
        hopHeight: .32,
        squash: .78,
        bumpSeconds: .10,
        yaw: {up: 0, down: Math.PI, left: Math.PI / 2, right: -Math.PI / 2},
    },
    ground: {grassY: .065, roadY: .01, railY: .07, waterY: -.12, logTop: .10, lilyTop: -.07},
    rows: {
        slots: 36,
        ahead: 16,
        startSafe: 2,
        decorX: 5,
        playableTree: [.10, .22],
        decorTree: .62,
        tallChance: .25, rockChance: .25,
        weights0: [.34, .38, .18, .10],
        weights1: [.22, .44, .20, .14],
        maxLength: [[1, 2], [1, 4], [1, 3], [1, 2]],
        difficultyRows: 150,
        prepareRows: 2,
        coinChance: .12,
    },
    traffic: {
        carSpeed: [1.6, 3.6], truckSpeed: [1.3, 2.6], speedBonus: .6,
        truckChance: .3,
        perLane: [2, 4],
        wrapHalfWidth: 12,
        carHalfLength: .91, truckHalfLength: 1.45, halfDepth: .38,
        playerHalfWidth: .22, playerHalfDepth: .22,
    },
    river: {
        logSpeed: [1.0, 2.2],
        logLengths: [2, 3, 4],
        gap: [1.2, 3.6],
        carryLimitX: 5.2,
        lilyChance: .3, lilyPads: [3, 5],
    },
    rail: {
        trainSpeed: 24,
        wagons: 4, carLength: 2.5,
        idle: [3.0, 7.0],
        warning: 1.1,
        halfDepth: .42,
    },
    eagle: {
        scrollSpeed: [.32, .60],
        margin: 4.5,
        backLimit: 4,
        swoopSeconds: .55, carrySeconds: .9,
    },
    death: {
        restartDelay: .8,
        flatY: .14, flatXZ: 1.35,
        sinkSeconds: .45,
    },
    hud: {font: "fonts/retro.ttf", fontSize: 32, x: 18, y: 14, topSize: 16, coinSize: 24,
        title: ["CHICKEN", "HOP"], titleSize: 48},
    pools: {
        grass: 36, grass_alt: 36, grass_b: 36, grass_alt_b: 36, ripple: 36, road: 36, road_marked: 36,
        water: 36, rail: 36,
        tree: 225, tree_tall: 90, rock: 45,
        car_purple: 33, car_cyan: 33, car_orange: 33, truck: 40,
        log2: 36, log3: 36, log4: 30,
        train_loco: 9, train_wagon: 36, signal: 9, signal_light: 9,
        lily: 45, coin: 24,
    },
    budgets: {
        sourceTriangles: 12000,
        reportedRamBytes: 20 * 1024 * 1024,
        vramBytes: 3.5 * 1024 * 1024,
        cpuP95Ms: 16.67,
    },
    particles: {
        counts: [36, 24, 12, 16, 6],
    },
    coin: {height: .42, spin: 3.2, bob: .06},
    multi: {
        startGap: 1,
        maxGap: 12,
        focusOffset: -1.2,
        maxDrift: 1.5,
        mergeEpsilon: .06,
        divider: 3,
        headHeight: .98,
    },
    audio: {
        volume: 90,
        panWidth: 8, panMax: 70,
        near: 2, far: 9,
        gain: {hop: .55, land_log: .8, land_lily: .7, bell: .6},
        streamVolume: {title: 70, ambience: 55}, fadeMs: 700,
    },
    juice: {
        shakeSeconds: .35, shakeAmount: .22,
        logDip: .07, dipSeconds: .25,
        lilyBob: .015,
        breathe: .035, breatheRate: 5,
        lookYaw: .55, lookRate: .9,
        rippleDrift: .35, rippleStill: .18,
        panelFade: .3,
    },
    measurement: {cpuFrames: 600, maxEvents: 64},
};
